[2024-08-08T20:18:30.109+0400] {processor.py:157} INFO - Started process (PID=6813) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:18:30.110+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:18:30.110+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:18:30.110+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:18:30.113+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:18:30.112+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:18:30.113+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:18:30.113+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:18:30.113+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:18:30.120+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2024-08-08T20:19:19.357+0400] {processor.py:157} INFO - Started process (PID=6864) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:19:19.358+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:19:19.359+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:19:19.359+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:19:19.361+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:19:19.360+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:19:19.361+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:19:19.361+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:19:19.361+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:19:19.367+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-08-08T20:20:04.520+0400] {processor.py:157} INFO - Started process (PID=6912) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:20:04.521+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:20:04.521+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:20:04.521+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:20:04.524+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:20:04.523+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:20:04.524+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:20:04.524+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:20:04.524+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:20:04.530+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-08-08T20:20:43.976+0400] {processor.py:157} INFO - Started process (PID=6954) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:20:43.977+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:20:43.977+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:20:43.977+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:20:43.980+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:20:43.979+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:20:43.980+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:20:43.980+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:20:43.980+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:20:43.989+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-08T20:21:26.387+0400] {processor.py:157} INFO - Started process (PID=6999) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:21:26.389+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:21:26.390+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:21:26.389+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:21:26.393+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:21:26.392+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:21:26.393+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:21:26.393+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:21:26.393+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:21:26.401+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-08T20:22:07.518+0400] {processor.py:157} INFO - Started process (PID=7042) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:22:07.520+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:22:07.520+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:22:07.520+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:22:07.523+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:22:07.522+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:22:07.523+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:22:07.523+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:22:07.523+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:22:07.531+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-08T20:22:52.640+0400] {processor.py:157} INFO - Started process (PID=7089) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:22:52.642+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:22:52.642+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:22:52.642+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:22:52.644+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:22:52.644+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:22:52.644+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:22:52.644+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:22:52.644+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:22:52.651+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2024-08-08T20:23:35.452+0400] {processor.py:157} INFO - Started process (PID=7156) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:23:35.453+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:23:35.454+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:23:35.454+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:23:35.457+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:23:35.456+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:23:35.458+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:23:35.457+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:23:35.458+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:23:35.468+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-08-08T20:24:21.479+0400] {processor.py:157} INFO - Started process (PID=7203) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:24:21.480+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:24:21.481+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:24:21.481+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:24:21.484+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:24:21.483+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:24:21.484+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:24:21.484+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:24:21.484+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:24:21.491+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-08-08T20:25:09.293+0400] {processor.py:157} INFO - Started process (PID=7259) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:25:09.294+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:25:09.295+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:25:09.295+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:25:09.297+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:25:09.297+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:25:09.298+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:25:09.298+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:25:09.298+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:25:09.304+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-08-08T20:25:52.542+0400] {processor.py:157} INFO - Started process (PID=7305) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:25:52.543+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T20:25:52.544+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:25:52.544+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:25:52.547+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:25:52.546+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T20:25:52.547+0400] {logging_mixin.py:151} INFO - [2024-08-08T20:25:52.547+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T20:25:52.547+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T20:25:52.558+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-08-08T22:09:43.752+0400] {processor.py:157} INFO - Started process (PID=9525) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:09:43.755+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:09:43.756+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:09:43.755+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:09:43.759+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:09:43.758+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:09:43.759+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:09:43.759+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:09:43.759+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:09:43.767+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-08-08T22:10:30.680+0400] {processor.py:157} INFO - Started process (PID=10079) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:10:30.682+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:10:30.684+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:10:30.683+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:10:30.689+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:10:30.688+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:10:30.689+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:10:30.689+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:10:30.689+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:10:30.702+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-08T22:11:19.001+0400] {processor.py:157} INFO - Started process (PID=10586) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:11:19.003+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:11:19.005+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:11:19.004+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:11:19.009+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:11:19.009+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:11:19.010+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:11:19.010+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:11:19.010+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:11:19.025+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-08T22:12:09.481+0400] {processor.py:157} INFO - Started process (PID=11010) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:12:09.484+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:12:09.485+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:12:09.484+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:12:09.488+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:12:09.487+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:12:09.488+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:12:09.488+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:12:09.488+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:12:09.502+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-08T22:12:58.274+0400] {processor.py:157} INFO - Started process (PID=11386) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:12:58.278+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:12:58.279+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:12:58.278+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:12:58.283+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:12:58.281+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:12:58.283+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:12:58.283+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:12:58.284+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:12:58.294+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-08T22:13:45.305+0400] {processor.py:157} INFO - Started process (PID=11839) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:13:45.307+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:13:45.308+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:13:45.308+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:13:45.312+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:13:45.311+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:13:45.312+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:13:45.312+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:13:45.313+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:13:45.326+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-08T22:14:32.919+0400] {processor.py:157} INFO - Started process (PID=12412) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:14:32.922+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:14:32.923+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:14:32.923+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:14:32.927+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:14:32.926+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:14:32.927+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:14:32.927+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:14:32.927+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:14:32.940+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-08T22:15:24.566+0400] {processor.py:157} INFO - Started process (PID=12816) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:15:24.569+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:15:24.570+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:15:24.569+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:15:24.574+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:15:24.573+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:15:24.574+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:15:24.574+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:15:24.575+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:15:24.588+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-08T22:16:15.331+0400] {processor.py:157} INFO - Started process (PID=13294) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:16:15.334+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:16:15.335+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:16:15.334+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:16:15.338+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:16:15.337+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:16:15.338+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:16:15.338+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:16:15.338+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:16:15.349+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-08-08T22:17:06.525+0400] {processor.py:157} INFO - Started process (PID=13891) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:17:06.527+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:17:06.528+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:17:06.528+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:17:06.532+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:17:06.531+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:17:06.532+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:17:06.532+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:17:06.532+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:17:06.540+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-08-08T22:17:44.284+0400] {processor.py:157} INFO - Started process (PID=14185) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:17:44.287+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:17:44.289+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:17:44.288+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:17:44.292+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:17:44.291+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:17:44.292+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:17:44.292+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:17:44.292+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:17:44.301+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-08-08T22:18:35.975+0400] {processor.py:157} INFO - Started process (PID=14588) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:18:35.977+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:18:35.978+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:18:35.977+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:18:35.981+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:18:35.981+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:18:35.981+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:18:35.981+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:18:35.982+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:18:35.992+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-08-08T22:19:13.492+0400] {processor.py:157} INFO - Started process (PID=14880) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:19:13.496+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:19:13.496+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:19:13.496+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:19:13.499+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:19:13.499+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:19:13.499+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:19:13.499+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:19:13.500+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:19:13.513+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-08T22:20:00.556+0400] {processor.py:157} INFO - Started process (PID=15275) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:20:00.559+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:20:00.560+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:20:00.560+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:20:00.564+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:20:00.563+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:20:00.564+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:20:00.564+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:20:00.564+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:20:00.573+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-08-08T22:20:51.480+0400] {processor.py:157} INFO - Started process (PID=15684) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:20:51.483+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:20:51.483+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:20:51.483+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:20:51.486+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:20:51.486+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:20:51.486+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:20:51.486+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:20:51.486+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:20:51.497+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-08-08T22:21:44.857+0400] {processor.py:157} INFO - Started process (PID=16208) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:21:44.860+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:21:44.862+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:21:44.861+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:21:44.867+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:21:44.866+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:21:44.867+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:21:44.867+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:21:44.867+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:21:44.876+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-08T22:22:35.719+0400] {processor.py:157} INFO - Started process (PID=16601) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:22:35.722+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:22:35.723+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:22:35.722+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:22:35.727+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:22:35.726+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:22:35.727+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:22:35.727+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:22:35.727+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:22:35.738+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-08T22:23:26.496+0400] {processor.py:157} INFO - Started process (PID=17086) to work on /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:23:26.499+0400] {processor.py:829} INFO - Processing file /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-08T22:23:26.501+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:23:26.500+0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:23:26.507+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:23:26.506+0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-08T22:23:26.507+0400] {logging_mixin.py:151} INFO - [2024-08-08T22:23:26.507+0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-08T22:23:26.508+0400] {processor.py:841} WARNING - No viable dags retrieved from /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-08T22:23:26.525+0400] {processor.py:179} INFO - Processing /home/eduardo/airflow_venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
